adding babyagi
error:
Creating ai-ticket_babyagi_run ...
Traceback (most recent call last):
  File "/app/babyagi.py", line 14, in <module>
    import chromadb
  File "/usr/local/lib/python3.11/site-packages/chromadb/__init__.py", line 1, in <module>
    import chromadb.config
  File "/usr/local/lib/python3.11/site-packages/chromadb/config.py", line 1, in <module>
    from pydantic import BaseSettings
  File "/usr/local/lib/python3.11/site-packages/pydantic/__init__.py", line 218, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/_migration.py", line 294, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.4/u/import-error
ERROR: 1